/* runtime-config.js */
/* This file is generated at runtime by Cloud Run */
/* DO NOT hardcode secrets here */

window.__RUNTIME_CONFIG__ = {
  REACT_APP_FIREBASE_API_KEY: "__REACT_APP_FIREBASE_API_KEY__",
  REACT_APP_FIREBASE_AUTH_DOMAIN: "__REACT_APP_FIREBASE_AUTH_DOMAIN__",
  REACT_APP_FIREBASE_PROJECT_ID: "__REACT_APP_FIREBASE_PROJECT_ID__",
  REACT_APP_FIREBASE_STORAGE_BUCKET: "__REACT_APP_FIREBASE_STORAGE_BUCKET__",
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "__REACT_APP_FIREBASE_MESSAGING_SENDER_ID__",
  REACT_APP_FIREBASE_APP_ID: "__REACT_APP_FIREBASE_APP_ID__",

  // Optional but useful
  BUILD_ENV: "__BUILD_ENV__",
  BUILD_VERSION: "__BUILD_VERSION__"
};
